# Site settings
title: Global ICT Program
email: linhtd@soict.hust.edu.vn
description: "Chương trình đào tạo kỹ sư toàn cầu về công nghệ thông tin"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
