# Site settings
title: Global ICT Program
email: linhtd@soict.hust.edu.vn
description: "Chương trình đào tạo kỹ sư toàn cầu về công nghệ thông tin"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

includes:
  - _pages

# Output
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "+07:00" # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones